- name: Downloading & Installing Essentials
  run: |
    Invoke-WebRequest -Uri "https://gitlab.com/chamod2/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
    if ($?) { cmd /c Downloads.bat } else { Write-Error "Failed to download Downloads.bat" }
    
